# The URL of the resource pack hosting service, which must end with a /
# You should probably not change this.
resource-pack-host-url: http://49.12.188.159/

# Whether players should be kicked when they reject the server resource pack
kick-upon-reject: false

# The message that will be sent to kicked players who rejected the server resource pack.
# This message is only used when kick-upon-reject is true.
force-reject-message: "You must accept the server resource pack. If you didn't get the chance to accept it, check out https://knokko.github.io/resource-pack-host/accept.html"

# The message that will be sent to players who rejected the server resource pack.
# This message is only used when kick-upon-reject is false.
# If you leave this empty, the players won't get any message.
optional-reject-message: "You rejected the server resource pack. If you would like to use it but didn't get the chance to accept it, check out https://knokko.github.io/resource-pack-host/accept.html"

# Whether players should be kicked when their minecraft client fails to download the server resource pack
kick-upon-failed-download: false

# The message that will be sent to kicked players who failed to download the server resource pack.
# This message will only be sent when kick-upon-failed-download is true
force-failed-message: "You must use the server resource pack, but the download failed. Please try again."

# The message that will be sent to players who failed to download the server resource pack.
# This message will only be sent when kick-upon-failed-download is false
optional-failed-message: "Downloading the server resource pack failed for some reason. You can retry by reconnecting to the server. If this keeps happening, contact the admin."
