name: "ResourcePack"
main: "nl.knokko.resourcepack.ResourcePackPlugin"
version: "1.2"
commands:
  resourcepack:
    description: "Change the server resource pack and/or view its status"
    usage: "/rpack changeid <id> [world]"
    aliases: ["rpack"]
