name: build
run-name: Builds the plug-in for Java 8
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: resource-pack-plugin
          path: build/libs/resource-pack-plugin.jar
